baseURL = "https://fteychene.github.io/vagrant-ansible-epsi"
languageCode = "fr-FR"
title = "Vagrant Ansible Getting Started"

theme = "code-editor"

publishDir = "docs"

[params]
    author = "Francois Teychen√©"
    locale = "fr-FR"